version: 2
project_name: helm-release-pruner
release:
  prerelease: auto
  github:
    owner: FairwindsOps
    name: helm-release-pruner
builds:
  - id: helm-release-pruner
    binary: helm-release-pruner
    main: ./cmd/pruner
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    ldflags:
      - -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -s -w
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    goos:
      - linux
      - darwin
      - windows
    ignore:
      - goos: windows
        goarch: arm64
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
brews:
  - name: helm-release-pruner
    repository:
      owner: FairwindsOps
      name: homebrew-tap
    directory: Formula
    description: Automatically delete old Helm releases
    test: |
      system "#{bin}/helm-release-pruner --version"

dockers:
- image_templates:
  - "quay.io/fairwinds/helm-release-pruner:{{ .FullCommit }}-amd64"
  - "quay.io/fairwinds/helm-release-pruner:{{ .Tag }}-amd64"
  - "quay.io/fairwinds/helm-release-pruner:v{{ .Major }}-amd64"
  - "quay.io/fairwinds/helm-release-pruner:v{{ .Major }}.{{ .Minor }}-amd64"
  use: buildx
  dockerfile: Dockerfile
  build_flag_templates:
  - "--platform=linux/amd64"
  extra_files:
  - go.mod
  - go.sum
  - cmd
  - pkg
- image_templates:
  - "quay.io/fairwinds/helm-release-pruner:{{ .Tag }}-arm64v8"
  - "quay.io/fairwinds/helm-release-pruner:v{{ .Major }}-arm64v8"
  - "quay.io/fairwinds/helm-release-pruner:v{{ .Major }}.{{ .Minor }}-arm64v8"
  use: buildx
  goarch: arm64
  goos: linux
  dockerfile: Dockerfile
  build_flag_templates:
  - "--platform=linux/arm64/v8"
  extra_files:
  - go.mod
  - go.sum
  - cmd
  - pkg
- image_templates:
  - "quay.io/fairwinds/helm-release-pruner:{{ .Tag }}-armv7"
  - "quay.io/fairwinds/helm-release-pruner:v{{ .Major }}-armv7"
  - "quay.io/fairwinds/helm-release-pruner:v{{ .Major }}.{{ .Minor }}-armv7"
  use: buildx
  goarch: arm
  goarm: 7
  goos: linux
  dockerfile: Dockerfile
  build_flag_templates:
  - "--platform=linux/arm/v7"
  extra_files:
  - go.mod
  - go.sum
  - cmd
  - pkg
docker_manifests:
- name_template: quay.io/fairwinds/helm-release-pruner:{{ .Tag }}
  image_templates:
  - "quay.io/fairwinds/helm-release-pruner:{{ .Tag }}-amd64"
  - "quay.io/fairwinds/helm-release-pruner:{{ .Tag }}-arm64v8"
  - "quay.io/fairwinds/helm-release-pruner:{{ .Tag }}-armv7"
- name_template: quay.io/fairwinds/helm-release-pruner:v{{ .Major }}
  image_templates:
  - "quay.io/fairwinds/helm-release-pruner:v{{ .Major }}-amd64"
  - "quay.io/fairwinds/helm-release-pruner:v{{ .Major }}-arm64v8"
  - "quay.io/fairwinds/helm-release-pruner:v{{ .Major }}-armv7"
- name_template: quay.io/fairwinds/helm-release-pruner:v{{ .Major }}.{{ .Minor }}
  image_templates:
  - "quay.io/fairwinds/helm-release-pruner:v{{ .Major }}.{{ .Minor }}-amd64"
  - "quay.io/fairwinds/helm-release-pruner:v{{ .Major }}.{{ .Minor }}-arm64v8"
  - "quay.io/fairwinds/helm-release-pruner:v{{ .Major }}.{{ .Minor }}-armv7"
